version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: setuptools
    versions:
    - 53.1.0
    - 54.1.0
    - 54.1.1
    - 54.1.2
    - 54.1.3
    - 54.2.0
    - 56.0.0
  - dependency-name: pytest
    versions:
    - 6.2.3
  - dependency-name: sphinx
    versions:
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
  - dependency-name: twine
    versions:
    - 3.4.0
    - 3.4.1
  - dependency-name: importlib-metadata
    versions:
    - 3.6.0
    - 3.7.0
    - 3.7.2
    - 3.7.3
  - dependency-name: queenbee-local
    versions:
    - 0.3.3
    - 0.3.4
